[env:esp32dev]

platfrom = espressif32@6.7.0
board = esp32dev
framework = arduino 

monitor_speed = 115200

lib_deps = 
 zinggjm/GxEPD2@^1.6.0
 adafruit/Adafruit GFX Library@^1.11.9
 earlephilhower/ESP8266Audio@^2.0.0
 greiman/SdFat@^2.2.2
